[versions]
appium = "10.0.0"
detekt = "1.23.8"
dokka = "2.1.0"
junit = "6.0.0"
kotlin = "2.0.0"
kotlinter = "5.2.0"
kover = "0.9.3"
mockk = "1.14.6"
selenide = "7.12.0"
vanniktech = "0.34.0"

[libraries]
appium = { module = "io.appium:java-client", version.ref = "appium" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
selenide-appium = { module = "com.codeborne:selenide-appium", version.ref = "selenide" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
vanniktech = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech" }
